<?php
namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use App\Support\ApiResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class AdminController extends Controller
{
    private function admin(Request $r){return $r->attributes->get('auth_user');}
    private function audit(Request $r,string $action,string $type,string|int $id,mixed $before=null,mixed $after=null):void{DB::table('audit_logs')->insert(['actor_user_id'=>$this->admin($r)->id,'action'=>$action,'entity_type'=>$type,'entity_id'=>(string)$id,'before_json'=>$before?json_encode($before):null,'after_json'=>$after?json_encode($after):null,'ip_address'=>$r->ip(),'request_id'=>$r->attributes->get('request_id'),'created_at'=>now()]);}
    public function dashboard(){return ApiResponse::success(['residents'=>DB::table('residents')->whereNull('deleted_at')->where('is_active',true)->count(),'active_letters'=>DB::table('letter_requests')->whereIn('status',['SUBMITTED','IN_REVIEW','APPROVED'])->count(),'unpaid_bills'=>DB::table('dues_bills')->where('status','UNPAID')->count(),'arrears'=>(float)DB::table('dues_bills')->where('status','UNPAID')->sum('total_amount'),'waiting_chats'=>DB::table('chat_sessions')->where('status','WAITING')->count()]);}
    public function residents(Request $r){$q=$this->residentBaseQuery();if(($s=$r->input('search'))!==null&&$s!==''){$field=$r->input('search_field');$q->where(function($x)use($s,$field){match($field){'nik'=>$x->where('r.nik','like',"%$s%"),'nama','full_name'=>$x->where('r.full_name','like',"%$s%"),'no_kk','family_card_number'=>$x->where('h.family_card_number','like',"%$s%"),default=>$x->where('r.nik','like',"%$s%")->orWhere('r.full_name','like',"%$s%")->orWhere('h.family_card_number','like',"%$s%")};});}$p=$q->orderBy('r.full_name')->paginate(min((int)$r->input('per_page',25),100));return ApiResponse::success($p->items(),200,['current_page'=>$p->currentPage(),'last_page'=>$p->lastPage(),'total'=>$p->total()]);}
    public function residentShow(int $id){$x=$this->residentBaseQuery()->where('r.id',$id)->first();return $x?ApiResponse::success($x):ApiResponse::error('NOT_FOUND','Warga tidak ditemukan.',404);}
    public function residentCreate(Request $r){$v=$this->residentData($r);$id=DB::table('residents')->insertGetId($v+['created_at'=>now(),'updated_at'=>now()]);$this->audit($r,'RESIDENT_CREATED','resident',$id,null,$v);return $this->residentShow($id);}
    public function residentUpdate(Request $r,int $id){$before=DB::table('residents')->where('id',$id)->whereNull('deleted_at')->first();if(!$before)return ApiResponse::error('NOT_FOUND','Warga tidak ditemukan.',404);$v=$this->residentData($r,true);DB::table('residents')->where('id',$id)->update($v+['updated_at'=>now()]);$this->audit($r,'RESIDENT_UPDATED','resident',$id,$before,$v);return $this->residentShow($id);}
    public function residentDelete(Request $r,int $id){$before=DB::table('residents')->where('id',$id)->whereNull('deleted_at')->first();if(!$before)return ApiResponse::error('NOT_FOUND','Warga tidak ditemukan.',404);DB::table('residents')->where('id',$id)->update(['is_active'=>false,'deleted_at'=>now(),'updated_at'=>now()]);$this->audit($r,'RESIDENT_DELETED','resident',$id,$before);return ApiResponse::success(['deleted'=>true]);}
    private function residentData(Request $r,bool $partial=false):array{$this->mergeLegacyResidentInput($r);$p=$partial?'sometimes':'required';$v=$r->validate(['nik'=>[$p,'string','max:32','unique:residents,nik'.($partial?','.$r->route('id'):'')],'household_id'=>'sometimes|nullable|exists:households,id','family_card_number'=>'sometimes|nullable|string|max:32','full_name'=>[$p,'string','max:160'],'birth_place'=>'sometimes|nullable|string|max:120','birth_date'=>'sometimes|nullable|date','gender'=>'sometimes|nullable|in:MALE,FEMALE,Laki-laki,Perempuan','address'=>[$p,'string','max:2000'],'religion'=>'sometimes|nullable|string|max:40','marital_status'=>'sometimes|nullable|string|max:40','occupation'=>'sometimes|nullable|string|max:120','nationality'=>'sometimes|string|max:80','id_valid_until'=>'sometimes|nullable|string|max:40','family_relationship'=>'sometimes|nullable|string|max:60','legacy_photo_path'=>'sometimes|nullable|string|max:500','is_active'=>'sometimes|boolean']);if(isset($v['gender']))$v['gender']=$this->normalizeGender($v['gender']);if(array_key_exists('id_valid_until',$v))$v['id_valid_until']=$this->normalizeLegacyDate($v['id_valid_until']);if(array_key_exists('family_card_number',$v)){ $kk=trim((string)($v['family_card_number']??'')); unset($v['family_card_number']); $v['household_id']=$kk===''?null:$this->ensureHousehold($kk,$v['address']??$r->input('address','-')); }return $v;}
    public function userLinkResident(Request $r){$v=$r->validate(['username'=>'required|string|max:120','nik'=>'required|string|max:32']);$residentId=DB::table('residents')->where('nik',$v['nik'])->whereNull('deleted_at')->value('id');if(!$residentId)return ApiResponse::error('NOT_FOUND','Warga tidak ditemukan.',404);$updated=DB::table('users')->where('username',$v['username'])->update(['resident_id'=>$residentId,'updated_at'=>now()]);return $updated?ApiResponse::success(['linked'=>true]):ApiResponse::error('NOT_FOUND','User tidak ditemukan.',404);}
    private function residentBaseQuery(){return DB::table('residents as r')->leftJoin('households as h','h.id','=','r.household_id')->whereNull('r.deleted_at')->select('r.*','h.family_card_number');}
    private function mergeLegacyResidentInput(Request $r):void{$map=['nama'=>'full_name','tanggal_lahir'=>'birth_date','jenis_kelamin'=>'gender','status_perkawinan'=>'marital_status','kewarganegaraan'=>'nationality','berlaku_hingga'=>'id_valid_until','status_hubungan'=>'family_relationship','foto'=>'legacy_photo_path','no_kk'=>'family_card_number'];foreach($map as $old=>$new){if($r->has($old)&&!$r->has($new))$r->merge([$new=>$r->input($old)]);}}
    private function normalizeGender(?string $value):?string{return match($value){'Laki-laki','MALE'=>'MALE','Perempuan','FEMALE'=>'FEMALE',default=>$value};}
    private function normalizeLegacyDate(?string $value):?string{$value=trim((string)$value);return preg_match('/^\d{4}-\d{2}-\d{2}$/',$value)?$value:null;}
    private function ensureHousehold(string $kk,string $address):int{$existing=DB::table('households')->where('family_card_number',$kk)->value('id');if($existing)return (int)$existing;return DB::table('households')->insertGetId(['family_card_number'=>$kk,'address'=>$address?:'-','created_at'=>now(),'updated_at'=>now()]);}
    public function household(int $id){$h=DB::table('households')->where('id',$id)->first();return $h?ApiResponse::success(['household'=>$h,'members'=>DB::table('residents')->where('household_id',$id)->whereNull('deleted_at')->get()]):ApiResponse::error('NOT_FOUND','Keluarga tidak ditemukan.',404);}
    public function householdCreate(Request $r){$v=$r->validate(['family_card_number'=>'required|string|max:32|unique:households,family_card_number','address'=>'required|string|max:2000','rt'=>'nullable|string|max:5','rw'=>'nullable|string|max:5']);$id=DB::table('households')->insertGetId($v+['created_at'=>now(),'updated_at'=>now()]);$this->audit($r,'HOUSEHOLD_CREATED','household',$id,null,$v);return ApiResponse::success(DB::table('households')->find($id),201);}
    public function householdUpdate(Request $r,int $id){$before=DB::table('households')->where('id',$id)->first();if(!$before)return ApiResponse::error('NOT_FOUND','Keluarga tidak ditemukan.',404);$v=$r->validate(['family_card_number'=>'sometimes|string|max:32|unique:households,family_card_number,'.$id,'address'=>'sometimes|string|max:2000','rt'=>'sometimes|nullable|string|max:5','rw'=>'sometimes|nullable|string|max:5']);DB::table('households')->where('id',$id)->update($v+['updated_at'=>now()]);$this->audit($r,'HOUSEHOLD_UPDATED','household',$id,$before,$v);return ApiResponse::success(DB::table('households')->find($id));}

    public function news(Request $r){return ApiResponse::success(DB::table('news')->whereNull('deleted_at')->orderByDesc('created_at')->orderByDesc('id')->get());}
    public function newsCreate(Request $r){$this->mergeLegacyNewsInput($r);$v=$r->validate(['title'=>'required|string|max:200','content'=>'required|string','image_media_id'=>'nullable|exists:media_files,id','legacy_image_path'=>'sometimes|nullable|string|max:500','status'=>'sometimes|in:DRAFT,PUBLISHED']);$id=DB::table('news')->insertGetId($v+['created_by'=>$this->admin($r)->id,'updated_by'=>$this->admin($r)->id,'published_at'=>($v['status']??'DRAFT')==='PUBLISHED'?now():null,'created_at'=>now(),'updated_at'=>now()]);$this->audit($r,'NEWS_CREATED','news',$id,null,$v);return ApiResponse::success(DB::table('news')->find($id),201);}
    public function newsUpdate(Request $r,int $id){$this->mergeLegacyNewsInput($r);$before=DB::table('news')->where('id',$id)->whereNull('deleted_at')->first();if(!$before)return ApiResponse::error('NOT_FOUND','Berita tidak ditemukan.',404);$v=$r->validate(['title'=>'sometimes|string|max:200','content'=>'sometimes|string','image_media_id'=>'sometimes|nullable|exists:media_files,id','legacy_image_path'=>'sometimes|nullable|string|max:500','status'=>'sometimes|in:DRAFT,PUBLISHED,ARCHIVED']);DB::table('news')->where('id',$id)->update($v+['updated_by'=>$this->admin($r)->id,'updated_at'=>now()]);$this->audit($r,'NEWS_UPDATED','news',$id,$before,$v);return ApiResponse::success(DB::table('news')->find($id));}
    private function mergeLegacyNewsInput(Request $r):void{if($r->has('judul')&&!$r->has('title'))$r->merge(['title'=>$r->input('judul')]);if($r->has('isi')&&!$r->has('content'))$r->merge(['content'=>$r->input('isi')]);if($r->has('gambar')&&!$r->has('legacy_image_path'))$r->merge(['legacy_image_path'=>$r->input('gambar')]);}
    public function newsPublish(Request $r,int $id){$n=DB::table('news')->where('id',$id)->whereNull('deleted_at')->update(['status'=>'PUBLISHED','published_at'=>now(),'updated_by'=>$this->admin($r)->id,'updated_at'=>now()]);if(!$n)return ApiResponse::error('NOT_FOUND','Berita tidak ditemukan.',404);$this->audit($r,'NEWS_PUBLISHED','news',$id);return ApiResponse::success(DB::table('news')->find($id));}
    public function newsDelete(Request $r,int $id){$n=DB::table('news')->where('id',$id)->whereNull('deleted_at')->update(['deleted_at'=>now(),'updated_by'=>$this->admin($r)->id,'updated_at'=>now()]);if(!$n)return ApiResponse::error('NOT_FOUND','Berita tidak ditemukan.',404);$this->audit($r,'NEWS_DELETED','news',$id);return ApiResponse::success(['deleted'=>true]);}

    public function letters(Request $r){$q=$this->letterBaseQuery();if($s=$r->input('status'))$q->where('l.status',$s);return ApiResponse::success($q->orderByDesc('l.id')->get());}
    public function letterShow(string $id){$x=$this->letterBaseQuery()->where(fn($q)=>$this->letterIdWhere($q,$id))->first();return $x?ApiResponse::success($x):ApiResponse::error('NOT_FOUND','Pengajuan tidak ditemukan.',404);}
    public function letterTransition(Request $r,string $id,string $target){$map=['review'=>'IN_REVIEW','approve'=>'APPROVED','reject'=>'REJECTED','complete'=>'COMPLETED'];$to=$map[$target]??null;$row=DB::table('letter_requests')->where(fn($q)=>$this->letterIdWhere($q,$id,''))->first();if(!$row||!$to)return ApiResponse::error('NOT_FOUND','Pengajuan/aksi tidak ditemukan.',404);$v=$r->validate(['admin_note'=>'nullable|string|max:3000','letter_number'=>'nullable|string|max:120','result_media_id'=>'nullable|exists:media_files,id','legacy_file_path'=>'nullable|string|max:500','legacy_file_name'=>'nullable|string|max:255']);if(isset($v['letter_number']))$v['letter_number']=$this->uniqueLetterNumber($v['letter_number'],(int)$row->id);$update=$v+['status'=>$to,'reviewed_by'=>$this->admin($r)->id,'reviewed_at'=>now(),'updated_at'=>now()];if(isset($v['legacy_file_path'])||isset($v['legacy_file_name']))$update['legacy_generated_at']=now();if($to==='COMPLETED')$update['completed_at']=now();DB::table('letter_requests')->where('id',$row->id)->update($update);$this->audit($r,'LETTER_'.$to,'letter_request',$row->id,$row,$update);return $this->letterShow((string)$row->id);}
    private function letterBaseQuery(){return DB::table('letter_requests as l')->join('residents as x','x.id','=','l.resident_id')->leftJoin('households as h','h.id','=','x.household_id')->select('l.*','x.nik','x.full_name','x.birth_place','x.birth_date','x.address','x.religion','x.occupation','x.family_relationship','h.family_card_number');}
    private function letterIdWhere($q,string $id,string $prefix='l.'):void{if(ctype_digit($id))$q->where($prefix.'id',(int)$id);else$q->where($prefix.'public_id',$id);}
    private function uniqueLetterNumber(?string $number,int $ignoreId):?string{$base=trim((string)$number);if($base==='')return $number;if(!DB::table('letter_requests')->where('letter_number',$base)->where('id','<>',$ignoreId)->exists())return $base;for($i=2;$i<1000;$i++){$suffix='-'.$i;$candidate=mb_substr($base,0,120-mb_strlen($suffix)).$suffix;if(!DB::table('letter_requests')->where('letter_number',$candidate)->where('id','<>',$ignoreId)->exists())return $candidate;}return mb_substr($base,0,105).'-'.now()->format('YmdHis');}

    public function periods(){return ApiResponse::success(DB::table('billing_periods')->orderByDesc('period')->get());}
    public function periodCreate(Request $r){$v=$r->validate(['period'=>['required','regex:/^[0-9]{4}-(0[1-9]|1[0-2])$/','unique:billing_periods,period'],'rt_fee'=>'required|numeric|min:0','waste_fee'=>'required|numeric|min:0']);$id=DB::table('billing_periods')->insertGetId($v+['status'=>'DRAFT','created_by'=>$this->admin($r)->id,'created_at'=>now(),'updated_at'=>now()]);$this->audit($r,'BILLING_PERIOD_CREATED','billing_period',$id,null,$v);return ApiResponse::success(DB::table('billing_periods')->find($id),201);}
    public function periodPublish(Request $r,int $id){return DB::transaction(function()use($r,$id){$p=DB::table('billing_periods')->where('id',$id)->lockForUpdate()->first();if(!$p)return ApiResponse::error('NOT_FOUND','Periode tidak ditemukan.',404);DB::table('residents')->whereNull('deleted_at')->where('is_active',true)->orderBy('id')->each(function($x)use($p){$this->upsertLegacyBill($p->id,$x->id,$p->rt_fee,$p->waste_fee);});DB::table('billing_periods')->where('id',$id)->update(['status'=>'PUBLISHED','published_at'=>now(),'updated_at'=>now()]);$this->audit($r,'BILLING_PERIOD_PUBLISHED','billing_period',$id);return ApiResponse::success(['published'=>true]);});}
    public function bills(Request $r){$q=DB::table('dues_bills as d')->join('billing_periods as p','p.id','=','d.billing_period_id')->join('residents as x','x.id','=','d.resident_id')->select('d.*','p.period','x.nik','x.full_name');if($s=$r->input('status'))$q->where('d.status',$s);if($p=$r->input('period'))$q->where('p.period',$p);return ApiResponse::success($q->orderByDesc('p.period')->orderByDesc('d.id')->get());}
    public function legacyGenerateBills(Request $r){$v=$r->validate(['period'=>['required','regex:/^[0-9]{4}-(0[1-9]|1[0-2])$/'],'rt_fee'=>'required|numeric|min:0','waste_fee'=>'required|numeric|min:0']);return DB::transaction(function()use($r,$v){$periodId=DB::table('billing_periods')->where('period',$v['period'])->value('id');if($periodId){DB::table('billing_periods')->where('id',$periodId)->update(['rt_fee'=>$v['rt_fee'],'waste_fee'=>$v['waste_fee'],'status'=>'PUBLISHED','published_at'=>now(),'updated_at'=>now()]);}else{$periodId=DB::table('billing_periods')->insertGetId($v+['status'=>'PUBLISHED','created_by'=>$this->admin($r)->id,'published_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);}$affected=0;DB::table('residents')->whereNull('deleted_at')->where('is_active',true)->orderBy('id')->each(function($x)use($periodId,$v,&$affected){$this->upsertLegacyBill($periodId,$x->id,$v['rt_fee'],$v['waste_fee']);$affected++;});$this->audit($r,'LEGACY_BILLS_GENERATED','billing_period',$periodId,null,$v);return ApiResponse::success(['affected'=>$affected,'billing_period_id'=>$periodId]);});}
    private function upsertLegacyBill(int $periodId,int $residentId,$rtFee,$wasteFee):void{$total=$rtFee+$wasteFee;$existing=DB::table('dues_bills')->where('billing_period_id',$periodId)->where('resident_id',$residentId)->first();if($existing){DB::table('dues_bills')->where('id',$existing->id)->update(['rt_fee'=>$rtFee,'waste_fee'=>$wasteFee,'total_amount'=>$total,'updated_at'=>now()]);return;}DB::table('dues_bills')->insert(['billing_period_id'=>$periodId,'resident_id'=>$residentId,'rt_fee'=>$rtFee,'waste_fee'=>$wasteFee,'total_amount'=>$total,'status'=>'UNPAID','paid_at'=>null,'note'=>null,'created_at'=>now(),'updated_at'=>now()]);}
    public function billStatus(Request $r,int $id,string $target){$status=$target==='mark-paid'?'PAID':($target==='mark-unpaid'?'UNPAID':null);$row=DB::table('dues_bills')->where('id',$id)->first();if(!$row||!$status)return ApiResponse::error('NOT_FOUND','Tagihan/aksi tidak ditemukan.',404);$v=$r->validate(['method'=>'nullable|in:CASH,TRANSFER,OTHER','reference'=>'nullable|string|max:120','note'=>'nullable|string|max:500']);return DB::transaction(function()use($r,$id,$row,$status,$v){DB::table('dues_bills')->where('id',$id)->update(['status'=>$status,'paid_at'=>$status==='PAID'?now():null,'note'=>$v['note']??null,'updated_at'=>now()]);if($status==='PAID'){DB::table('payment_records')->insert(['dues_bill_id'=>$id,'amount'=>$row->total_amount,'method'=>$v['method']??'CASH','reference'=>$v['reference']??null,'recorded_by'=>$this->admin($r)->id,'paid_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);$this->notifyBillPaid($id);}else{$this->clearBillPaidNotification($id);}$this->audit($r,'BILL_'.$status,'dues_bill',$id,$row);return ApiResponse::success(DB::table('dues_bills')->find($id));});}
    private function billNotificationInfo(int $id){return DB::table('dues_bills as d')->join('billing_periods as p','p.id','=','d.billing_period_id')->join('residents as x','x.id','=','d.resident_id')->leftJoin('users as u','u.resident_id','=','d.resident_id')->where('d.id',$id)->select('d.*','p.period','x.full_name','u.id as user_id')->first();}
    private function clearBillReminderNotifications(int $userId,int $billId):void{DB::table('notifications')->where('user_id',$userId)->whereIn('type',['DUES_REMINDER','tagihan'])->where(function($q)use($billId){$q->where('data_json','like','%"bill_id":'.$billId.'%')->orWhere('data_json','like','%"bill_id":"'.$billId.'"%')->orWhere('data_json','like','%"ref_id":'.$billId.'%')->orWhere('data_json','like','%"ref_id":"'.$billId.'"%');})->delete();}
    private function clearBillPaidNotification(int $billId):void{$info=$this->billNotificationInfo($billId);if(!$info||!$info->user_id)return;DB::table('notifications')->where('user_id',$info->user_id)->where('type','DUES_PAID')->where(function($q)use($billId){$q->where('data_json','like','%"bill_id":'.$billId.'%')->orWhere('data_json','like','%"bill_id":"'.$billId.'"%');})->delete();}
    private function notifyBillPaid(int $billId):void{$info=$this->billNotificationInfo($billId);if(!$info||!$info->user_id)return;$this->clearBillReminderNotifications((int)$info->user_id,$billId);DB::table('notifications')->insert(['id'=>(string)Str::ulid(),'user_id'=>$info->user_id,'type'=>'DUES_PAID','title'=>'Pembayaran iuran '.$info->period.' diterima','body'=>'Halo '.$info->full_name.', pembayaran iuran RT dan uang sampah bulan '.$info->period.' sebesar Rp'.number_format($info->total_amount,0,',','.').' sudah tercatat lunas. Terima kasih.','data_json'=>json_encode(['bill_id'=>$billId]),'created_at'=>now()]);}
    public function notifyBills(Request $r){$v=$r->validate(['bill_ids'=>'required|array|min:1|max:500','bill_ids.*'=>'integer|exists:dues_bills,id']);$count=0;foreach(DB::table('dues_bills as d')->join('users as u','u.resident_id','=','d.resident_id')->whereIn('d.id',$v['bill_ids'])->where('d.status','UNPAID')->select('d.*','u.id as user_id')->get() as $b){DB::table('notifications')->insert(['id'=>(string)Str::ulid(),'user_id'=>$b->user_id,'type'=>'DUES_REMINDER','title'=>'Pengingat Iuran','body'=>'Tagihan sebesar Rp'.number_format($b->total_amount,0,',','.').' belum dibayar.','data_json'=>json_encode(['bill_id'=>$b->id]),'created_at'=>now()]);$count++;}return ApiResponse::success(['notified'=>$count]);}
    public function legacyNotification(Request $r){$v=$r->validate(['nik'=>'required|string|max:32','title'=>'required|string|max:180','body'=>'required|string','type'=>'nullable|string|max:80','ref_id'=>'nullable|integer']);$userId=DB::table('users as u')->join('residents as r','r.id','=','u.resident_id')->where('r.nik',$v['nik'])->value('u.id');if(!$userId)return ApiResponse::success(['created'=>false,'reason'=>'USER_NOT_FOUND']);$id=(string)Str::ulid();DB::table('notifications')->insert(['id'=>$id,'user_id'=>$userId,'type'=>$v['type']??'LEGACY','title'=>$v['title'],'body'=>$v['body'],'data_json'=>json_encode(['ref_id'=>$v['ref_id']??null]),'created_at'=>now()]);return ApiResponse::success(['created'=>true,'id'=>$id]);}
    public function mediaUpload(Request $r){$v=$r->validate(['file'=>'required|file|max:10240|mimes:jpg,jpeg,png,gif,webp,pdf']);$f=$v['file'];$path=$f->store('uploads');$id=DB::table('media_files')->insertGetId(['disk'=>config('filesystems.default'),'path'=>$path,'original_name'=>$f->getClientOriginalName(),'mime_type'=>$f->getMimeType(),'size_bytes'=>$f->getSize(),'checksum_sha256'=>hash_file('sha256',$f->getRealPath()),'uploaded_by'=>$this->admin($r)->id,'created_at'=>now(),'updated_at'=>now()]);return ApiResponse::success(DB::table('media_files')->find($id),201);}
}
