<?php
namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use App\Support\ApiResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ChatController extends Controller
{
    private function user(Request $r){return $r->attributes->get('auth_user');}
    public function start(Request $r){$u=$this->user($r);return DB::transaction(function()use($u){$this->closeDuplicateCitizenSessions((int)$u->id);$existing=DB::table('chat_sessions')->where('citizen_user_id',$u->id)->whereIn('status',['WAITING','ACTIVE'])->orderByDesc('updated_at')->lockForUpdate()->first();if($existing)return ApiResponse::success($existing);$id=(string)Str::ulid();DB::table('chat_sessions')->insert(['id'=>$id,'citizen_user_id'=>$u->id,'status'=>'WAITING','started_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);return ApiResponse::success(DB::table('chat_sessions')->where('id',$id)->first(),201);});}
    public function current(Request $r){$u=$this->user($r);$this->closeDuplicateCitizenSessions((int)$u->id);$x=DB::table('chat_sessions')->where('citizen_user_id',$u->id)->whereIn('status',['WAITING','ACTIVE'])->orderByDesc('updated_at')->first();return $x?ApiResponse::success($x):ApiResponse::success(null);}
    public function adminSessions(Request $r){$this->closeStaleEmptySessions();$q=DB::table('chat_sessions as s')->join('users as u','u.id','=','s.citizen_user_id')->select('s.*','u.username');if($status=$r->input('status'))$q->where('s.status',$status);else$q->whereIn('s.status',['WAITING','ACTIVE']);$rows=$q->orderByDesc('s.updated_at')->get();$seen=[];$deduped=[];foreach($rows as $s){$key=(int)$s->citizen_user_id;if(isset($seen[$key])){DB::table('chat_sessions')->where('id',$s->id)->update(['status'=>'CLOSED','closed_at'=>now(),'updated_at'=>now()]);continue;}$seen[$key]=true;$deduped[]=$s;}usort($deduped,fn($a,$b)=>strcmp((string)$a->started_at,(string)$b->started_at));return ApiResponse::success($deduped);}
    public function assign(Request $r,string $id){$admin=$this->user($r);return DB::transaction(function()use($r,$id,$admin){$s=DB::table('chat_sessions')->where('id',$id)->lockForUpdate()->first();if(!$s)return ApiResponse::error('NOT_FOUND','Sesi tidak ditemukan.',404);if($s->status!=='WAITING'&&$s->assigned_admin_id!=$admin->id)return ApiResponse::error('ALREADY_ASSIGNED','Sesi telah diambil admin lain.',409);DB::table('chat_sessions')->where('id',$id)->update(['assigned_admin_id'=>$admin->id,'status'=>'ACTIVE','assigned_at'=>now(),'updated_at'=>now()]);DB::table('admin_presence')->insertOrIgnore(['admin_user_id'=>$admin->id,'status'=>'ONLINE','active_chat_count'=>0,'created_at'=>now(),'updated_at'=>now()]);DB::table('admin_presence')->where('admin_user_id',$admin->id)->increment('active_chat_count',1,['status'=>'ONLINE','last_seen_at'=>now(),'updated_at'=>now()]);return ApiResponse::success(DB::table('chat_sessions')->where('id',$id)->first());});}
    public function messages(Request $r,string $id){if(!$this->participant($r,$id))return ApiResponse::error('FORBIDDEN','Bukan peserta sesi.',403);$q=DB::table('chat_messages as m')->leftJoin('users as u','u.id','=','m.sender_user_id')->where('m.chat_session_id',$id)->select('m.*','u.role as sender_role','u.username as sender_name')->orderBy('m.sent_at');if($after=$r->input('after'))$q->where('m.id','>',$after);return ApiResponse::success($q->limit(200)->get());}
    public function send(Request $r,string $id){if(!$this->participant($r,$id))return ApiResponse::error('FORBIDDEN','Bukan peserta sesi.',403);$v=$r->validate(['message_type'=>'sometimes|in:TEXT,FILE','body'=>'nullable|string|max:5000','media_file_id'=>'nullable|exists:media_files,id']);$type=$v['message_type']??'TEXT';if($type==='TEXT'&&blank($v['body']??null))return ApiResponse::error('VALIDATION_ERROR','Pesan teks wajib diisi.',422);if($type==='FILE'&&!isset($v['media_file_id']))return ApiResponse::error('VALIDATION_ERROR','File wajib diisi.',422);$mid=(string)Str::ulid();DB::table('chat_messages')->insert(['id'=>$mid,'chat_session_id'=>$id,'sender_user_id'=>$this->user($r)->id,'message_type'=>$type,'body'=>$v['body']??null,'media_file_id'=>$v['media_file_id']??null,'sent_at'=>now()]);return ApiResponse::success(DB::table('chat_messages')->where('id',$mid)->first(),201);}
    public function close(Request $r,string $id){return DB::transaction(function()use($r,$id){$u=$this->user($r);$s=DB::table('chat_sessions')->where('id',$id)->lockForUpdate()->first();if(!$s)return ApiResponse::error('NOT_FOUND','Sesi tidak ditemukan.',404);$allowed=($u->role==='CITIZEN'&&(int)$s->citizen_user_id===(int)$u->id)||($u->role==='ADMIN'&&(!$s->assigned_admin_id||(int)$s->assigned_admin_id===(int)$u->id));if(!$allowed)return ApiResponse::error('FORBIDDEN','Bukan peserta sesi.',403);if($s->status==='CLOSED')return ApiResponse::success(['closed'=>true]);$assignedAdmin=$s->assigned_admin_id?:($u->role==='ADMIN'?$u->id:null);DB::table('chat_sessions')->where('id',$id)->update(['assigned_admin_id'=>$assignedAdmin,'status'=>'CLOSED','closed_at'=>now(),'updated_at'=>now()]);if($assignedAdmin){$p=DB::table('admin_presence')->where('admin_user_id',$assignedAdmin)->lockForUpdate()->first();if($p)DB::table('admin_presence')->where('admin_user_id',$assignedAdmin)->update(['active_chat_count'=>max(0,(int)$p->active_chat_count-1),'updated_at'=>now()]);}return ApiResponse::success(['closed'=>true]);});}
    public function presence(Request $r){$v=$r->validate(['status'=>'required|in:OFFLINE,ONLINE,BUSY']);$id=$this->user($r)->id;DB::table('admin_presence')->updateOrInsert(['admin_user_id'=>$id],['status'=>$v['status'],'last_seen_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);return ApiResponse::success(DB::table('admin_presence')->where('admin_user_id',$id)->first());}
    private function participant(Request $r,string $id):bool{$u=$this->user($r);$s=DB::table('chat_sessions')->where('id',$id)->first();return $s&&(($u->role==='CITIZEN'&&(int)$s->citizen_user_id===(int)$u->id)||($u->role==='ADMIN'&&(int)$s->assigned_admin_id===(int)$u->id));}
    private function closeDuplicateCitizenSessions(int $userId):void{$sessions=DB::table('chat_sessions')->where('citizen_user_id',$userId)->whereIn('status',['WAITING','ACTIVE'])->orderByDesc('updated_at')->get();$keep=true;foreach($sessions as $s){if($keep){$keep=false;continue;}DB::table('chat_sessions')->where('id',$s->id)->update(['status'=>'CLOSED','closed_at'=>now(),'updated_at'=>now()]);}}
    private function closeStaleEmptySessions():void{$sessions=DB::table('chat_sessions')->whereIn('status',['WAITING','ACTIVE'])->where('updated_at','<',now()->subMinutes(5))->get();foreach($sessions as $s){$hasMessage=DB::table('chat_messages')->where('chat_session_id',$s->id)->exists();if(!$hasMessage)DB::table('chat_sessions')->where('id',$s->id)->update(['status'=>'CLOSED','closed_at'=>now(),'updated_at'=>now()]);}}
}
